-- The vehicles involved in more than 1 crash:

SELECT 
    VEHICLE_LICENSE_NUMBER, 
    COUNT(*) AS ACCIDENTS,
    MAX(REPORT_DATE) AS LATEST_REPORT_DATE,
    MAX(REPORT_STATE) AS LATEST_REPORT_STATE
FROM crash_2024oct_short
GROUP BY VEHICLE_LICENSE_NUMBER
HAVING COUNT(*) > 1
ORDER BY ACCIDENTS DESC;
