-- 4.2 Trim Extra Spaces

-- Disable safe update mode
SET SQL_SAFE_UPDATES = 0;

 UPDATE crash_2024oct_short
 		SET 
        REPORT_NUMBER = TRIM(REPORT_NUMBER),
        REPORT_STATE = TRIM(REPORT_STATE),
 		WEATHER_CONDITION_DESC = TRIM(WEATHER_CONDITION_DESC),
        ROAD_SURFACE_CONDITION_DESC = TRIM(ROAD_SURFACE_CONDITION_DESC),
        LIGHT_CONDITION_DESC = TRIM(LIGHT_CONDITION_DESC),
        VEHICLE_LICENSE_NUMBER = TRIM(VEHICLE_LICENSE_NUMBER);

-- Re-enable safe update mode
SET SQL_SAFE_UPDATES = 1;

-- =================================
