-- Alaska daily

SELECT REPORT_DATE, count(REPORT_NUMBER) as Alaska_num_of_crashes -- , WEATHER_CONDITION_DESC AS WEATHER
FROM crash_2024oct_clean
WHERE REPORT_STATE = "AK"
GROUP BY REPORT_DATE -- , WEATHER_CONDITION_DESC
ORDER BY REPORT_DATE
;

-- Alabama daily

SELECT REPORT_DATE, count(REPORT_NUMBER) as Alabama_num_of_crashes -- , WEATHER_CONDITION_DESC AS WEATHER
FROM crash_2024oct_clean
WHERE REPORT_STATE = "AL"
GROUP BY REPORT_DATE -- , WEATHER_CONDITION_DESC
ORDER BY REPORT_DATE
;

-- Two states daily

SELECT REPORT_DATE, count(REPORT_NUMBER) as Two_States_num_of_crashes -- , WEATHER_CONDITION_DESC AS WEATHER
FROM crash_2024oct_clean
-- WHERE REPORT_STATE = "AK"
GROUP BY REPORT_DATE -- , WEATHER_CONDITION_DESC
ORDER BY REPORT_DATE
;